/* 將 src/ 入面嘅檔案砌成一個獨立嘅 index.html。
   用法：node build.mjs
   同時會出一份 src/model.gen.mjs 畀 Node 測試用，
   咁模型就只有一份 source of truth，唔會同遊戲行緊嗰份走樣。 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = dirname(fileURLToPath(import.meta.url));
const src = f => readFileSync(join(root, 'src', f), 'utf8');

/* i18n.js 要行第一 —— 佢定義 LANGS，跟住每個 lang/*.js 自己註冊入去。
   語言檔本身只係資料，冇邏輯，所以擺喺最前面唔會有 side effect。 */
const ORDER = ['i18n.js', 'lang/zh-HK.js', 'lang/zh-TW.js', 'lang/zh-TW.scen.js',
               'lang/en.js', 'lang/en.scen.js',
               'model.js', 'engine.js', 'bias.js', 'judge.js',
               'scen1.js', 'scen2.js', 'scen3.js', 'audio.js', 'ui.js'];

const script = ORDER
  .map(f => `\n/* ===================== ${f} ===================== */\n` + src(f))
  .join('\n');

/* 出街位置係 docs/game/ —— 網站真正 publish 嗰份。
   assets/ 亦都住喺嗰度，全世界只有一份。呢個 folder 淨係放源碼同工具，
   唔會俾 mkdocs publish 上網。 */
const OUT = join(root, '..', 'docs', 'game', 'index.html');
const html = src('shell.html').replace('/*__SCRIPT__*/', () => script);
writeFileSync(OUT, html);

/* Node 測試用嘅副本：同一份 source，加返 export。
   模型 / 引擎 / 場景只有一份 source of truth，測試同遊戲唔會走樣。
   judge.js 要 bias.js 嘅 location（瀏覽器嘢），所以 test 側自己 stub。 */
const TEST_FILES = ['i18n.js', 'lang/zh-HK.js', 'lang/zh-TW.js', 'lang/zh-TW.scen.js',
  'lang/en.js', 'lang/en.scen.js',
  'model.js', 'engine.js', 'bias.js', 'judge.js', 'scen1.js', 'scen2.js', 'scen3.js'];
const EXPORTS = ['TURNS', 'START', 'CONTRIB0', 'yearAt', 'ageAt', 'REG',
  'makePath', 'blankDecision', 'newSim', 'step', 'runMike', 'replay',
  'newGame', 'mikeAt', 'phaseOf', 'drift', 'applyChoice', 'optionsFor',
  'commitChoice', 'isRuined', 'SCEN_ROOKIE', 'SCEN_MID', 'SCEN_VET',
  'monteCarlo', 'attribute', 'judge', 'levelOf', 'ENDING_INFO',
  /* i18n —— 畀 test.mjs 查譯文覆蓋率同金額換算 */
  'LANGS', 'LANG', 'DEFAULT_LANG', 'setLang', 'applyLocale', 'applyScenLocale',
  't', 'fmt', 'LC', 'curRate', 'BIAS', 'CH', 'PHASE_LABEL'];
writeFileSync(join(root, 'src', 'game.gen.mjs'),
  '/* AUTO-GENERATED by build.mjs — do not edit; edit the files in src/ */\n' +
  TEST_FILES.map(f => `\n/* ---- ${f} ---- */\n` + src(f)).join('\n') +
  '\nexport {' + EXPORTS.join(', ') + '};\n');

const kb = n => (n / 1024).toFixed(1) + ' KB';
console.log('docs/game/index.html', kb(html.length));
console.log('  script        ', kb(script.length));
ORDER.forEach(f => console.log('   ' + f.padEnd(14), kb(src(f).length)));
